# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mturk_dev_db
  port: 5433
  password: harvey
  username: postgres

test:
  <<: *default
  database: mturk_test_db
  port: 5433
  password: harvey
  username: postgres

production:
  <<: *default
  database: mturk_prod_db
  port: 5433
  password: harvey
  username: postgres